---
title: "Measuring the Microbiome: Methods and Tools"
site: distill::distill_website
favicon: microscope_inferno.png
---

### Measuring the Microbiome  

```{r xaringan_extra_intro_mm1, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

xaringanExtra::embed_xaringan(url = "https://bjklab.github.io/EPID674_001_intro-to-microbiome-data/lecture_welcome-to-EPID674.html",
                              ratio = "16:9")



```
  
  
### Sequences to Counts  

```{r xaringan_extra_intro_mm2, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

xaringanExtra::embed_xaringan(url = "https://bjklab.github.io/EPID674_002_sequences-to-counts/lecture_sequences-to-count-data.html",
                              ratio = "16:9")



```
  
  
### Alpha Diversity  
  
```{r xaringan_extra_intro_mm5, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

xaringanExtra::embed_xaringan(url = "https://bjklab.github.io/EPID674_005_alpha-diversity/lecture_alpha-diversity.html",
                              ratio = "16:9")


```
  
  
### Beta Diversity  
  
```{r xaringan_extra_intro_mm6, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

xaringanExtra::embed_xaringan(url = "https://bjklab.github.io/EPID674_006_beta-diversity/lecture_beta-diversity.html",
                              ratio = "16:9")


```
  
  
### Regression Methods for Microbiome Data  
  
```{r xaringan_extra_intro_mm8, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

xaringanExtra::embed_xaringan(url = "https://bjklab.github.io/EPID674_008_microbiome-regression/lecture_microbiome-regression.html",
                              ratio = "16:9")


```
  
  
### More Regression Methods for Microbiome Data  
  
```{r xaringan_extra_intro_mm9, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

xaringanExtra::embed_xaringan(url = "https://bjklab.github.io/EPID674_009_more-microbiome-regression/lecture_more-microbiome-regression.html",
                              ratio = "16:9")


```

  
  

