---
title: "Projects"
site: distill::distill_website
favicon: microscope_white.png
---

```{r, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}



```

### mVACS: mRNA Vaccines for _C. difficile_ Suppression - Human Subjects Core (U19 AI174998 - Core C)    
  
We are contributing to a collaborative center with multidisciplinary scientists working to develop mRNA vaccine candidates to address the threat posed by recurrent _C. difficile_ infection. The human subjects core is focused on developing a clinical biorepository and prospective cohort to identify populations in whom vaccination strategies against _C. difficile_ will be most beneficial. Biorepository progress report <a href="biorepo_reports/biorepository_report_mVACS.html" target="_blank">here</a>.   
  
  
### Fecal microbiota transplantation to address colonization and environmental contamination with multidrug-resistant organisms (FACE-MDRO) (CDC U54-CK000610)    
  
We will perform fecal microbiota transplantation (FMT) at the conclusion of antibiotic therapy for MDRO infections to define the impact of FMT on eradicating MDRO colonization from the gastrointestinal tract. We will also determine how FMT administration impacts MDRO colonization in the healthcare environment.   
  
  
### Whole-genome sequencing to define SARS-CoV-2 variant populations during vaccine rollout in the Philadelphia metropolitan region (CDC BAA 200-2021-10986)  
  
We are (1) performing longitudinal, geographic sampling of COVID-19 cases; (2) applying viral whole genome sequencing (WGS) and comparative phylogenetic analysis to cases; and (3) integrating longitudinal vaccine distribution and community mobility data with the viral WGS data to understand how the phylodynamics of SARS-CoV-2 change as COVID-19 vaccination expands.    
  
  
### Metagenomic and whole-genome sequencing to define resistome evolution during antibiotic exposure and long-term acute care (CDC BAA 200-2018-02919)  
  
We are applying metagenomic sequencing to raw respiratory and gastrointestinal
tract specimens collected from a cohort of long-term acute care hospital (LTACH) patients with _Pseudomonas aeruginosa_ colonization to understand how commonly prescribed antibiotics impact the microbiome and resistome, as well as the evolution of _Pseudomonas_ colonization and antibiotic resistance.  
  
  
### Stool microbiome features to discriminate Clostridium difficile colonization and infection (CDC BAA 200-2016-91937)  
  
We are performing a cross-sectional study to determine the bacterial microbiome features that discriminate _C. difficile_ infection (CDI) from _C. difficile_ colonization, as well as microbiome features associated with risk for severe CDI and recurrent CDI.   
  
  
### Respiratory tract microbiome composition and risk for antibiotic-resistant lower respiratory infection during long-term acute care (CDC BAA 200-2016-91964)  

We developed a cohort of long-term acute care (LTACH) patients dependent on mechanical ventilation and at high risk for lower respiratory tract infection and performed dense, longitudinal sampling of the upper and lower respiratory tract, as well as the gastrointestinal tract, in order to understand the evolution of the bacterial microbiome during critical illness and the microbiome features that portend risk for LRTI, thus improving the ability to target diagnostic and infection prevention interventions.  
  
  
### Randomized clinical trial of fecal microbiota transplantation for severe and severe-complicated _C.difficile_ infection (CDC Southeastern Pennsylvania Adult and Pediatric Prevention Epicenter Network)  
  
A phase II, randomized trial to evaluate the safety and efficacy of fecal microbiota transplantation using the Penn Microbiome Therapy products for severe or severe-complicated/fulminate _C.difficile_ infection ([NCT03970200](https://clinicaltrials.gov/ct2/show/NCT03970200)).  
  
  
### Longitudinal analysis of respiratory tract microbiome change and sequence-based infection diagnosis during mechanical ventilation (K23 AI121485)
  
Bacterial pneumonia is a common and dangerous contributor to critical illness, during which patients depend on mechanical ventilators to assist their breathing. It may contribute to the initial need for mechanical ventilation, or it may complicate the course of mechanical ventilation. We are using deep sequencing methods to completely characterize the bacterial community of the respiratory tract over the full course of mechanical ventilation, thus improving understanding of how bacterial pneumonia occurs in critically ill patients, with implications for prevention, diagnosis, and treatment interventions.   
  
  
  