---
title: "COVID-19 in Kids and Adults"
description: |
  A population science journal club discussion.
author:
  - name: Brendan J. Kelly 
    url: https://github.com/bjklab
    affiliation: University of Pennsylvania
    affiliation_url: https://www.cceb.med.upenn.edu/bio/brendan-j-kelly-md-msce
date: 2021-03-31
preview: cover_slide.png
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE, error = FALSE)
library(metathis)
meta() %>%
  meta_description(
    "COVID-19 in Kids and Adults"
  ) %>% 
  meta_name("github-repo" = "bjklab/") %>% 
  meta_viewport() %>% 
  meta_social(
    title = "COVID-19 in Kids and Adults",
    url = "bjklab.org/posts/2021-03-31-covid-19-in-kids-and-adults",
    image = "cover_slide.png",
    image_alt = "The title slide",
    og_type = "blog",
    og_author = "Brendan J. Kelly",
    twitter_card_type = "summary",
    twitter_creator = "@bjk_lab"
  )
```

Today I had the opportunity to discuss SARS-CoV-2 transmission among kids and adults, drawing on a recent seroprevalence study. It was a pleasure to join the Penn DBEI's Population Science journal club. My slides are attached here.   
  
  
```{r xaringan_sarscov2_pediatric_seroprevalence, eval=TRUE, warning=FALSE, message=FALSE, echo=FALSE}

xaringanExtra::embed_xaringan(url = "https://bjklab.github.io/SARS-CoV-2_pediatric_seroprevalence/pediatric_sarscov2_seroprevalence.html",
                              ratio = "16:9")



```


